name = "dannys4Registry"
uuid = "9f77249a-6fbd-4d26-b4d2-2a8a3a053195"
repo = "https://github.com/dannys4/dannys4Registry"
description = "Registry for packages created by dannys4"

[packages]
7304c03a-8850-446d-9145-3faedd36b2b6 = { name = "SparseQuadrature", path = "S/SparseQuadrature" }
9d32bc2f-1c07-4c0c-b0b2-5edd4e076357 = { name = "MultivariateExpansions", path = "M/MultivariateExpansions" }
b97ecbdf-1535-430e-a7c7-b5702749f368 = { name = "MultiIndexing", path = "M/MultiIndexing" }
