name = "dannys4Registry"
uuid = "9f77249a-6fbd-4d26-b4d2-2a8a3a053195"
repo = "https://github.com/dannys4/dannys4Registry"
description = "Registry for packages created by dannys4"

[packages]
0af289be-425b-4145-9967-cdb935e32293 = { name = "SmallMCMC", path = "S/SmallMCMC" }
1fffb988-1a3a-4757-b9a7-a23a87666c1e = { name = "TransportBasedInference2", path = "T/TransportBasedInference2" }
7304c03a-8850-446d-9145-3faedd36b2b6 = { name = "SparseQuadrature", path = "S/SparseQuadrature" }
9d32bc2f-1c07-4c0c-b0b2-5edd4e076357 = { name = "MultivariateExpansions", path = "M/MultivariateExpansions" }
b97ecbdf-1535-430e-a7c7-b5702749f368 = { name = "MultiIndexing", path = "M/MultiIndexing" }
